# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('purchase_date', models.DateTimeField(verbose_name='date of purchase')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.User')),
            ],
        ),
    ]
