# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20160203_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['description'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['purchase_date', 'description']},
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
