# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 13:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20160210_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.DecimalValidator(4, 2), django.core.validators.MinValueValidator(limit_value=0.01)]),
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together=set([('user', 'category', 'purchase_date', 'description', 'price')]),
        ),
    ]
